# Generated by Django 5.1.2 on 2024-10-29 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studytable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=100)),
                ('Lastname', models.CharField(max_length=100)),
                ('Age', models.IntegerField()),
                ('Gender', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Mob', models.IntegerField()),
                ('Qualification', models.CharField(max_length=100)),
                ('Dob', models.DateField()),
                ('Username', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('Image', models.FileField(upload_to='')),
            ],
        ),
    ]
